# Generated by Django 5.2.1 on 2025-06-02 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('has_public_bathrooms', models.BooleanField(default=False)),
                ('has_playground', models.BooleanField(default=False)),
                ('has_basketball_court', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trip_images/')),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trips.park')),
            ],
        ),
    ]
